name: tickets
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=zenek
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    volumes:
      - ./init-multiple-dbs:/docker-entrypoint-initdb.d
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
  rabbitmq:
    image: rabbitmq:4-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: zenek
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 5
  availabilityapi:
    image: availabilityapi
    profiles: ["app"]
    build:
      context: .
      dockerfile: AvailabilityApi/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Logging__Console__FormatterName=simple
    volumes:
      - ~/.aspnet/https:/https:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  sales:
    image: sales
    profiles: ["app"]
    build:
      context: .
      dockerfile: Sales/Dockerfile
    ports:
      - "8082:8082"
      - "8083:8083"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8082;https://+:8083
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - Logging__Console__FormatterName=simple
      - ConnectionStrings__Availability=Host=postgres;Port=5433;Database=tickets-availability;Username=zenek;Password=secret
      - RabbitMQ__Host=rabbitmq
    volumes:
      - ~/.aspnet/https:/https:ro
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
